version: '2'

networks:
  find3-network:
    driver: bridge

services:
  server:
    container_name: server
    build: ./server/main
    restart: always
    volumes:
      - ./server/main:/go/src/github.com/schollz/find3/server/main/
    ports:
      - "11883:1883"
    networks:
      - find3-network
    links:
      - "ai:ai"
    ports:
      - "80:8005"
    env_file: ./server/main/.env
  ai:
    container_name: ai
    build: ./server/ai
    restart: always
    volumes:
      - ./server/ai:/app
    networks:
      - find3-network
    env_file: ./server/ai/.env
    ports:
      - "8002:8002"
